name: Update docs translation

on:
  pull_request:
    paths:
      - 'cookbook/**'
      - 'guide/**'

jobs:
  update-docs:
    name: Update docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.YIISOFT_GITHUB_TOKEN || github.token }}
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Use po4a
        uses: addnab/docker-run-action@v3
        with:
            image: arduanovdanil/po4a-fork:v0.73
            options: -v ${{ github.workspace }}:/src
            run: |
                cd _translations/guide
                po4a po4a.cfg
                cd ../cookbook
                po4a po4a.cfg
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update translation
          file_pattern: '_translations guide cookbook'
